/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Avator: typeof import('./components/avator.vue')['default']
    Children: typeof import('./components/children.vue')['default']
    Computed: typeof import('./components/computed.vue')['default']
    DeleteDialog: typeof import('./components/deleteDialog.vue')['default']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    Header: typeof import('./components/header/header.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Sidebar: typeof import('./components/sidebar/sidebar.vue')['default']
    TodoList: typeof import('./components/todoList.vue')['default']
  }
}
